### ISSUE TITLE
Chooses worst result instead of best

### ISSUE THREAD

**Issue by hctankred** [Mortal/yahtzee-react#1]
The logic chooses the weaker result instead of the best, when there is more than one valid result for a field.

Example:
You enter 1 1 1 6 6 6
For 3 of a kind, 3 is selected instead of 18.
The same occurs no matter the order of the input.

**Comment by Mortal** [comment]
I've looked through the code and indeed for 3 of a kind there's a bug. Have you noticed this issue with other rolls than 3 of a kind?

**Comment by Mortal** [comment]
Fix deployed
![image](https://user-images.githubusercontent.com/373639/74266998-859c2700-4d05-11ea-82cb-60c0b61f0846.png)
